### ISSUE TITLE
Spotify Redirect URI

### ISSUE THREAD

**Issue by dargmuesli** [itsaphel/tv-playlist-generator-cli#1]
The [redirect URI](https://github.com/itsaphel/tv-playlist-generator-cli/blob/master/src/main/java/io/indices/tvplaylistgenerator/streaming/Spotify.java#L27) for spotify apps should not be hardcoded. It is app-specific.

**Comment by itsaphel** [comment]
Yeah, planned to take care of that when I was going to push to git. This code is prematurely pushed so you can take a look at the specific code causing the issue (as you said you couldn't reproduce on your end), so there might be some hardcoded variables floating around.

That's just going to be moved to config.json.

For the purposes of this CLI app, the URL doesn't really matter, it's always going to be a dummy site. The point is really just to get an authorisation code for CLI usage.

**Comment by dargmuesli** [comment]
Yeah, I'll take a look at the song-playlist-problem today. The URL for this CLI app matters still though, as it is coupled to the client id & secret. If the URL does not match the one specified for the client id, Spotify will throw an error on the authorization page.
